# Configuration of the CI pipeline
name: 'Azure SAP HANA Deployment'
canonical: 'azure-sap-hana-stack'
description: 'This stack will deploy SAP HANA on a Azure VM'
keywords:
  - 'azure'
  - 'linux'
  - 'demo'
  - 'sap hana'
technologies:
  - technology: AZURE cloud
    version: n/a
author: 'OCB CSD OS Factory'
image: 'https://raw.githubusercontent.com/nbht/ocbosfactory/stacks/sapicon.png'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    terraform:
      path: 'terraform/azinfra.tf'
      destination: '($ project $)/terraform/($ environment $)/azinfra.tf'
    terraform-variable:
      path: 'terraform/azvariable.tf'
      destination: '($ project $)/terraform/($ environment $)/azvariable.tf'

  # Configuration of ansible for mount all disks
  ansible:
    ansible:
      path: 'ansible/mountfs.yml'
      destination: '($ project $)/ansible/($ environment $)-mountfs.yml'

